feat: готовая версия по итогу второго этапа разработки
yuliazherebtsova/lubimovka pull request #76
Opened 2021-09-17 07:44 UTC by yuliazherebtsova

2021-09-20 19:19 UTC, vgschevchenko commented on blocks/header/__social/header__social.css
>    border-left: 1px solid #232323;
От верхнего края до рамки должен быть отступ. 
http://joxi.ru/1A5bV9GsDgDdxr

2021-09-20 19:22 UTC, vgschevchenko commented on index.html
>      <section class="main-info content__section">
У подзаголовка указите корректные отступы. 
http://joxi.ru/bmoojOJI3V3Kdm

2021-09-20 19:24 UTC, vgschevchenko commented on index.html
>      <section class="main-info content__section">
Элемент с кнопкой и датой необходимо корректно расположить. 
Возможно указаны некорректные отступы. 
http://joxi.ru/vAWDjYOSgJgWnr

2021-09-20 19:26 UTC, vgschevchenko commented on index.html
>      <section class="main-info content__section">
Укажите корректные отступы или размер блока. 
http://joxi.ru/Q2Knvx1FL5Ljnm

2021-09-20 19:31 UTC, vgschevchenko commented on index.html
>      </section>
Обратите внимание на блок `authors` и его элементы. 
Указаны некорректные отступы между ними. 
http://joxi.ru/RmzX3gohY1YonA

2021-09-20 19:32 UTC, vgschevchenko commented on blocks/description-block/__video/description-block__video.css
>  .description-block__video {
Укажите корректную высоту для элемента. 
http://joxi.ru/BA0dV4GsMLM5KA

2021-09-20 19:34 UTC, vgschevchenko commented on blocks/description-block/__text/description-block__text.css
>  .description-block__text {
Обратите внимание на макет, как там оформлены абзацы. 
Например, абзацы следующие после первого в первой строке получают отступ. 
http://joxi.ru/82QVv7LSwLwEnA

2021-09-20 19:36 UTC, vgschevchenko commented on index.html
>        <h2 class="gallery__title">Заголовок блока с&nbsp;фотографиями</h2>
Расположение заголовка. 
http://joxi.ru/KAxea5JCZJZJKr

2021-09-20 19:38 UTC, vgschevchenko commented on index.html
>        </div>
Необходимо корректно выровнять или расположить элементы согласно макету. 
http://joxi.ru/Dr8KVnPUoQoQ3A

2021-09-20 19:39 UTC, vgschevchenko commented on index.html
>          <div class="reviews__pagination"></div>
От пагинации до кнопок указать корректный отступ. 
http://joxi.ru/Dr8KVnPUoQoQ3A

2021-09-20 19:42 UTC, vgschevchenko commented on index.html
>        <!-- Главный контейнер слайдера -->
У элемента слайдера или карточки укажите корректные отступы между блоками. 
http://joxi.ru/krDpw9RsK8K81r

2021-09-20 19:44 UTC, vgschevchenko commented on index.html
>    <footer class="footer page__section page__section_place_footer">
* Элементы в футере необходимо корректно расположить согласно макету. 
* Сравните с макетом высоту блока, отступы между элементами, отступы у блока. 
* http://joxi.ru/a2XVvenSwRwnKr

2021-09-20 19:45 UTC, vgschevchenko commented on index.html
>      </section>
Высота блока больше чем указано в макете. 
http://joxi.ru/a2XVvenSwRwnKr

2021-09-20 19:49 UTC, vgschevchenko commented on index.html
>      </section>
Для видео необходимо сделать темную подложку с кнопкой `play`. 
http://joxi.ru/nAyzRXJhgpgxlr

2021-09-20 20:40 UTC, vgschevchenko commented on blocks/header/header.css
>  .header {
Корректно выровнять элементы в блоке на мобильном. 
http://joxi.ru/4Ak3jOlHovoWEA

2021-09-20 20:42 UTC, vgschevchenko commented on index.html
>      <section class="main-info content__section">
На мобильном проблемы с отступами у элементов. 
Сейчас они выровнены по правому краю. 
http://joxi.ru/Q2Knvx1FL5Lnpm

2021-09-20 20:46 UTC, vgschevchenko commented on blocks/description/description.css
> +
Отступ на мобильных должен быть меньше .
http://joxi.ru/KAxea5JCZJZd5r

2021-09-20 20:47 UTC, vgschevchenko commented on index.html
>      </section>
На мобильных у элементов в данном блоке отступы указаны некорректно. 
http://joxi.ru/L21LVjGhRPR5lm

2021-09-20 20:48 UTC, vgschevchenko commented on blocks/description-block/__video/description-block__video.css
>  .description-block__video {
на мобильных размеры блока должны быть больше. 
http://joxi.ru/p278VL4sKyKMaA

2021-09-20 20:51 UTC, vgschevchenko commented on index.html
>            <div class="description-block__card-content">
Укажите корректные стили на мобильных: размеры отступов, элементов, текста. 
http://joxi.ru/zAN0v56Fv4vQYm

2021-09-20 20:52 UTC, vgschevchenko commented on blocks/gallery/__title/gallery__title.css
>  @media (max-width: 414px) {
Отступ на мобильных от элемента до изображений. 
http://joxi.ru/MAj0jMBFj0jzvm

2021-09-20 20:53 UTC, vgschevchenko commented on blocks/reviews/__header/reviews__header.css
>  .reviews__header {
Корректно выровнять элементы или указать верные размеры. 
http://joxi.ru/v29QVJGtZ1Z7p2

2021-09-20 20:55 UTC, vgschevchenko commented on index.html
>        <!-- Главный контейнер слайдера -->
У элемента карточки на мобильных указать корректно отступы. 
http://joxi.ru/VrwoZQzI7N7Zvr

2021-09-20 20:56 UTC, vgschevchenko commented on index.html
>        <!-- Главный контейнер слайдера -->
В карточке рецензии должна быть кнопка. 
http://joxi.ru/VrwoZQzI7N7Zvr

2021-09-20 20:57 UTC, vgschevchenko commented on index.html
>        <!-- Главный контейнер слайдера -->
Где-то потерялся отступ. 
http://joxi.ru/EA4NVp4IogobMm

2021-09-20 20:57 UTC, vgschevchenko commented on blocks/feedback/__title/feedback__title.css
> +@media screen and (max-width: 450px) {
Размер текста на мобильных. 
http://joxi.ru/n2Y8jzXsbqbMnm

2021-09-20 20:58 UTC, vgschevchenko commented on blocks/feedback/__prev-button/feedback__prev-button.css
>  .feedback__prev-button {
Необходимо или задать корректные размеры или выровнять согласно макету. 
http://joxi.ru/DmBXvEZhJEJ0vA

2021-09-20 21:02 UTC, vgschevchenko commented on index.html
>          <h2 class="feedback__title">Отзывы зрителей</h2>
Размер шрифта. 
http://joxi.ru/82QVv7LSwLwlqA

2021-09-20 21:02 UTC, vgschevchenko commented on index.html
>        <!-- Главный контейнер слайдера -->
Размер текста в данном элементе. 
http://joxi.ru/82QVv7LSwLwlqA

2021-09-20 21:03 UTC, vgschevchenko commented on index.html
>    </footer>
Не хватает бургер меню.

2021-09-20 21:03 UTC, vgschevchenko commented on index.html
>    </footer>
Элементы не выровнены. 
http://joxi.ru/Q2Knvx1FL5LNpm

2021-09-20 21:12 UTC, vgschevchenko commented on index.html
>      <button type="button" class="header__support-button header__support-button_hidden">
Модификатор должен быть "сложным" в том смысле, что его название должно формироваться по одному из принципу, например "ключ-значение".
https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

2021-09-20 21:13 UTC, vgschevchenko commented on index.html
>      <div class="header__social">
Для улучшения семантики перечисляемые блоки можно выделить в список `ul`. 
Обратите внимание, что у списков следует убрать стандартные стили: `margin`, `padding`, `list-style-type`

2021-09-20 21:23 UTC, vgschevchenko commented on blocks/card/__readmore/card__readmore.css
>  }
Указаны фиксированные значения высоты и ширины. 
Не пройдет переполнение текстом.

2021-09-20 21:30 UTC, vgschevchenko commented on blocks/reviews/__next-button/reviews__next-button.css
> +.reviews__next-button:before {
Общие стили для обоих псевдоэлементов лучше всего объединить.

2021-09-20 21:39 UTC, vgschevchenko commented
#### Разверните комментарий(⬇👇)

#### Ваша работа принята. 
 
Вы хорошо постарались. 
Работа оставила приятное впечатление.
Присутствует еще некоторые моменты, которые вы можете поправить, чтобы работа стала еще лучше. 
Желаю вам дальнейших успехов. 


Присутствуют ошибки, которые вам необходимо исправить, чтобы вы могли добавить работу к себе в портфолио. 
У вас для этого будет 2 итерации.
Работа будет принята, даже если после второй итерации у вас останутся ошибки. 
Вы справитесь, желаю вам успехов. 

После работой над ошибками, создайте корректный `Pull  Request` с последними изменениями и приложите ссылку. 

## Что понравилось:
 
* Хорошо заполнен README
* Верстка выполнена аккуратно.
* Код в `html` хорошо отформатирован.
* Достойное совпадение с макетом. 
* Используется семантические теги `main, h, p, ul, section, nav, header, footer` и т.д.
* Используются псевдоклассы. 
* Хорошо получился javascript. 
* Хорошо реализовали nested файловую структуру для проекта.
* Хорошо получился слайдер. Использовали хороший плагин, который сделал свою работу. 


## Оценка работы в целом: 

1. оценка на соответствие макетам ++/-
	* Присутствует моменты, которые отличаются от макета, например отступы между элементами, размеры элементов по высоте, контент в кнопках на планшетной версии, размеры и стиль иконок. 
2. насколько хорошо ведёт себя адаптив +
3. насколько семантична и валидна вёрстка на CSS +
4. оценка на применение БЭМ +
5. валидация качества кода, который написан на препроцессорах -
    1. структура файлов +
    2. использование mix-in и переменных -
6. проверка функциональности на js (все работает корректно и без ошибок) +

    1. Использование слайдера +
    2. Создание бургерного меню +
	

## То что важно поправить. 

* Необходимо сверить с макетами для всех разрешений и указать корректные отступы между блоками и их элементами.  
* Проверять промежуточные разрешения на предмет сломанной или не конкретной верстки.
* Для контентных или текстовых элементов используются фиксированные свойства высоты и ширины.

2021-09-22 08:53 UTC, spacehaz commented on index.html
>    </footer>
@vgschevchenko судя по всему это ошибка в макете. Эта кнопка должна быть наверху, она сползла вниз на макете судя по всему

2021-09-30 17:18 UTC, vgschevchenko commented on blocks/header/__social-decor/header__social-decor.css
> +.header__social-decor {
http://joxi.ru/RmzX3gohY1O4WA
Сравните с макетом данный момент. 
Рамки не спрошенные, от верхнего края присутствует отступ.

2021-09-30 17:22 UTC, vgschevchenko commented on blocks/page/__section/_place/page__section_place_footer.css
http://joxi.ru/gmvRKelsq9ZW1m
В данном блоке все еще остались ошибки из прошлой итерации. 
Например: 

- Укажите точные размеры изображения. 
- Проблемы с отступами между элементами, особенно между текстовыми.

2021-09-30 17:27 UTC, vgschevchenko commented on blocks/description/description.css
> +
http://joxi.ru/n2Y8jzXsbqnPym
В данном блоке все еще не исправлены отступы между элементам и размеры видео. 

- В данном блоке каждый абзацы начинается с красной строки или отступа. 
- Отступы между авторами пьесы больше чем необходимо по макету. 
- Нижние отступы между абзацами.

2021-09-30 17:29 UTC, vgschevchenko commented on blocks/gallery/__title/gallery__title.css
На десктопе необходимо выровнять заголовок, как показано в макете. 
http://joxi.ru/823OVjvU9V5Lk2

2021-09-30 17:35 UTC, vgschevchenko commented on blocks/reviews/__slide/reviews__slide.css
>  }
Проигнорировано из прошлой итерации. 

Отступы внутри блока между элементами, укажите корректные. 
http://joxi.ru/eAOqv4WT9NZPNm

2021-09-30 17:38 UTC, vgschevchenko commented on blocks/footer/footer.css
http://joxi.ru/nAyzRXJhgp3zXr
Футер не готов. 
Пишут тут, как общий комментарий. 

- Некорректные отступы между элементами. 
- Размер по высоте больше чем в макете. 
- Расположение колонок с ссылками.

2021-09-30 17:42 UTC, vgschevchenko commented on blocks/description/description.css
> +
Для видео должна быть сделана темная подложка с кнопкой `play`.
Сверьте с макетом данный момент. 
http://joxi.ru/ZrJVvqkSwY6Bnr
http://joxi.ru/KAgKjMBUEp9d5A

2021-09-30 17:51 UTC, vgschevchenko commented on blocks/description/description.css
> +@media screen and (max-width: 400px) {
На мобильных отступ сверху у серого блока должен быть больше. 
http://joxi.ru/LmGVv3nSwqn0br

2021-09-30 17:56 UTC, vgschevchenko commented on blocks/header/header.css
>    height: 62px;
Фиксированная высота для блока содержащего контентную информацию.

2021-09-30 17:57 UTC, vgschevchenko commented on blocks/header/header.css
>  @media screen and (max-width: 900px) {
На мобильных не указан корректно отступ сверху. 
http://joxi.ru/E2pvQkpS7RYNYr

2021-09-30 17:58 UTC, vgschevchenko commented on blocks/description/description.css
> +    row-gap: 0;
На мобильных в блоке авторов проблема с отступами между элементами. 
http://joxi.ru/J2bej5BC0do6lm

2021-09-30 17:59 UTC, vgschevchenko commented on blocks/description/description.css
> +
На мобильных для блока description__first укажите корректны отступы сверху и снизу.

2021-09-30 18:00 UTC, vgschevchenko commented on blocks/description/description.css
> +
На мобильном. 
http://joxi.ru/bmoojOJI3VQ4Em
Проблемы в следующем: 
- Размеры с видео. 
- Некорректно заданы отступы от видео до абзацев. 
- Некорректно заданы отступы между абзацами.

2021-09-30 18:04 UTC, vgschevchenko commented on blocks/description/description.css
> +
http://joxi.ru/D2PjvBdIqGa5or

Данный элемент блока не подогнан под макет. 

- Размеры самого блока. 
- Размеры текста

2021-09-30 18:05 UTC, vgschevchenko commented on blocks/gallery/__title/gallery__title.css
>  @media (max-width: 414px) {
Нижний отступ на мобильных от заголовка до изображений. 
http://joxi.ru/brRDv8KS7g3vj2

2021-09-30 18:06 UTC, vgschevchenko commented on blocks/reviews/__slide/reviews__slide.css
>  }
http://joxi.ru/nAyzRXJhgp3PXr
На мобильных не указаны корректные отступы между элементами в карточке.

2021-09-30 18:07 UTC, vgschevchenko commented on blocks/reviews/__slide/reviews__slide.css
>  }
Необходимо корректно расположить кнопки.
Выровнять по отношению к заголовку.  
http://joxi.ru/nAyzRXJhgp3PXr

2021-09-30 18:08 UTC, vgschevchenko commented on blocks/feedback/__title/feedback__title.css
> +@media screen and (max-width: 450px) {
Размер текста на мобильных. 
http://joxi.ru/LmGVv3nSwqnobr

2021-09-30 18:09 UTC, vgschevchenko commented on blocks/feedback/__next-button/feedback__next-button.css
>  .feedback__next-button {
Расположение и выравнивание кнопок на  мобильных. 

http://joxi.ru/LmGVv3nSwqnobr

2021-09-30 18:10 UTC, vgschevchenko commented on blocks/footer/footer.css
>  }
http://joxi.ru/YmEVvk3SwN3Oq2
На мобильных нижняя часть футера не доработана. 

- Расположение элементов. 
- Отступы между элементами.

2021-09-30 18:15 UTC, vgschevchenko commented on blocks/feedback/__title/feedback__title.css
>    }
Пишут тут, так как в другом месте недоступно. 

Размер текста  отзыва элементе должен быть меньше. 
http://joxi.ru/82QVv7LSwLwlqA

2021-09-30 18:17 UTC, vgschevchenko commented on blocks/header/__support-button/header__support-button.css
>    display: flex;
Корректно создать модификатор для кнопки. 

Модификатор должен быть "сложным" в том смысле, что его название должно формироваться по одному из принципу, например "ключ-значение".
https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

2021-09-30 18:19 UTC, vgschevchenko commented on blocks/reviews/__next-button/reviews__next-button.css
Общие стили для обоих псевдоэлементов лучше всего объединить.

Другими словами создать общий селекторе: 
class:before,
class:after {
тут общие стили
}

2021-09-30 18:25 UTC, vgschevchenko commented on index.html
> +    <nav class="header__mobile">
Два тега `nav` это будет лишней обёрткой.

2021-09-30 18:29 UTC, vgschevchenko commented on index.html
>      <div class="footer__mobile">
Мобильная версия футере будет лишней, это дублирование и нагромождение кода. 
Необходимо используя флекс или грид, корректно адаптировать блок футер, без дублей кода.

2021-09-30 18:34 UTC, vgschevchenko commented on blocks/button/button.css
> +.button:hover .main-info__arrow-left {
Присутствуют селектор совсем другого элемента. 
БЭМ не поддерживает такой подход .

2021-09-30 18:37 UTC, vgschevchenko commented on blocks/card/__readmore/card__readmore.css
> +.card__readmore:focus, .card__readmore:focus .card__readmore-arrow {
Дублируете .card__readmore:focus

2021-09-30 18:37 UTC, vgschevchenko commented on blocks/card/__readmore/card__readmore.css
> +.card__readmore:hover, .card__readmore:hover .card__readmore-arrow {
Дублируете .card__readmore:hover

2021-09-30 18:38 UTC, vgschevchenko commented on blocks/card/__readmore/card__readmore.css
> +.card__readmore:hover, .card__readmore:hover .card__readmore-arrow {
Как для ховер так и для фокуса одинаковые стили - их можно объеденить.

2021-09-30 18:42 UTC, vgschevchenko commented on blocks/feedback/__next-button/feedback__next-button.css
> +.feedback__next-button:before {
Для обоих псевдоэлементов применяются общие стили, их  можно объединить.

2021-09-30 18:47 UTC, vgschevchenko commented on blocks/feedback/__prev-button/feedback__prev-button.css
> +.feedback__prev-button::after {
Для обоих псевдоэлементов применяются общие стили, их можно объединить.

2021-09-30 18:54 UTC, vgschevchenko commented
#### Ваша работа принята. 

В целом вы неплохо постарались.
Но многие ошибки так и не были исправлены, особенно те, что касаются соответствия с макетом. 
Я советую вам хорошо пройтись по макетам и все подогнать, чтобы работа была более полной и завершенной. 

Вы справитесь, желаю вам успехов. 

## То что важно поправить. 

* Упросить верстку максимально насколько это возможно. Задействую флекс и грид в работе. 
* Убрать дубли в `css`. 
* В блоке `description` и вложенных в него блоках не проводилась работа. Отступы так и не были скорректированы с макетом. 
* В блоке `reviews` не проводилась работа над ошибками. Отступы между заголовков и текстом были взяты некорректно из макета. 
* В блоке аналогичная ситуация: отступы между элементами некорректные, расположение элементов в блоке. 
* Все еще остаются разночтения с макетом в некоторых блоках и элементах. Особенно это касается отступов, расположения или выравнивания элементов на странице.
* Многие ошибки не были вами исправлены из первой итерации.

2021-11-17 11:18 UTC, SmilingJey reviewed
Резюме

2021-11-17 11:18 UTC, SmilingJey commented on index.html
> +      <ul class="header__menu-decor">
комментарий

2021-11-17 11:18 UTC, SmilingJey commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
комментарий

2021-11-17 11:22 UTC, SmilingJey requested changes
Резюме

2021-11-17 11:22 UTC, SmilingJey commented on index.html
> +        <li><a href="#" class="header__link" target="_blank">История</a></li>
комментарий

2021-11-17 11:22 UTC, SmilingJey commented on index.html
> +        <li><a href="#" class="header__link" target="_blank">Новости</a></li>
комментарий

2023-03-23 02:26 UTC, merged